baseURL = "https://bosco-chanwoo.github.io/"
languageCode = "ko-kr"
title = "bosco"
theme = "PaperMod"
mainSections = ["study", "research"]

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "light"
  ShowToc = true
  math = true
  TocOpen = true
  TocSidebar = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

  # 홈 소개 카드
  [params.homeInfoParams]
    Title = "🐇 Welcome to STATsDL Playground"
    Content = "This is a page for posting statistical deep learning contents. "


 
  # (선택) 이메일 아이콘
  [[params.socialIcons]]
  name = "email"
  url = "mailto:bosco999@snu.ac.kr"

[menu]

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 10

  [[menu.main]]
    name = "Study"
    url = "/study/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]
